channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.6.1
  - attrs=21.4.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - cartopy=0.20.1
  - certifi=2022.5.18.1
  - click=8.1.3
  - cycler=0.11.0
  - dbus=1.13.6
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.10.4
  - geos=3.9.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.2
  - icu=69.1
  - iniconfig=1.1.1
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.83.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm13=13.0.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - ncurses=6.3
  - nspr=4.32
  - nss=3.78
  - numpy=1.22.4
  - openjpeg=2.4.0
  - openssl=3.0.3
  - packaging=21.3
  - pandas=1.3.5
  - pcre=8.45
  - pillow=9.1.1
  - pip=22.1.2
  - pluggy=1.0.0
  - proj=8.1.1
  - pthread-stubs=0.4
  - py=1.11.0
  - pyparsing=3.0.9
  - pyproj=3.2.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyshp=2.3.0
  - pytest=7.1.2
  - python=3.9.13
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.1
  - qt=5.12.9
  - readline=8.1.2
  - scipy=1.8.1
  - setuptools=59.8.0
  - shapely=1.7.1
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.1
  - tzdata=2022a
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
