name: pytrajplot
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - black=23.9.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cartopy=0.22.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfgv=3.3.1
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.1.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - distlib=0.3.7
  - exceptiongroup=1.1.3
  - expat=2.5.0
  - filelock=3.12.4
  - fontconfig=2.14.2
  - fonttools=4.42.1
  - freetype=2.12.1
  - geos=3.12.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - identify=2.5.29
  - iniconfig=2.0.0
  - isort=5.12.0
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=7.88.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libpq=12.15
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.16
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - ncurses=6.4
  - nodeenv=1.8.0
  - nspr=4.35
  - nss=3.92
  - numpy=1.26.0
  - openssl=3.1.3
  - packaging=23.1
  - pandas=2.1.1
  - pathspec=0.11.2
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - pluggy=1.3.0
  - ply=3.11
  - pre-commit=3.4.0
  - proj=9.2.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyparsing=3.1.1
  - pyproj=3.5.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyshp=2.3.1
  - pytest=7.4.2
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - setuptools=68.2.2
  - sip=6.6.2
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sqlite=3.43.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - ukkonen=1.0.1
  - virtualenv=20.24.4
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - pytrajplot==1.1.2
    - shapely==1.7.1
